# server
server:
  port: ${SERVER_PORT:8080}

# datasource
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:cars_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:sa}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${KEYCLOAK_PORT:8081}/realms/cars

keycloak:
  auth-server-url: http://keycloak:8080
  realm: cars
  resource: car_client
  credentials:
    secret: QPK51eJt1AZoYfyYnH4SsuXWt5uEOZM7
